AllCops:
  Exclude:
    - rspec-retry_ex.gemspec
    - tmp/**/*
    - Rakefile
    - Gemfile
    - spec/spec_helper.rb

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/IndentationConsistency:
  EnforcedStyle: normal

Metrics/CyclomaticComplexity:
  Max: 10

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
